### ISSUE TITLE
landingview-page

### ISSUE THREAD

**Issue by JainSid96** [aishwaryasharmaccoew/SeProject#12]
This page will show a basic landing page view of all the products on the ecomm website
Will contains
          1. Card View of the Products
          2. Side Menu for Filters
          3. Top Menu Bar consisting - Logo, Search, Cart, and Account Details
          4. Bottom Footer

**Comment by aishwaryasharmaccoew** [comment]
below commit integrates this page to the final project
https://github.com/aishwaryasharmaccoew/SeProject/commit/408a64e2cc366a13f5a973ad777bed4d3c372791
