### ISSUE TITLE
As a User, I want to View Categories and Items so that I can select the knife I want.

### ISSUE THREAD

**Issue by JainSid96** [aishwaryasharmaccoew/SeProject#18]
**1. User Story**
As a user, shopping on the website will want to select the product based on the shown selection of products as if they were in a physical store.

**2. Acceptance Criteria**
Landing page, that will list 10-15 knives in a grid view along with their specific details and prices.

**3. Definition of Done**
Users can scroll up and down, hover over the product grid and view their prices, color selection, availability, and prior ratings.

**4. Functional Req**
FR01 - The users shall be able to view the categories on the application’s home page.
FR02 - The users shall be able to view items in different categories.
FR03 - The users shall be able to add items to the cart.
FR04 - The users shall be able to view more information about an item before adding it to the cart
FR05 - The users shall be able to able view the shopping cart.
FR06 - The users shall be able to browse through the available items.

**Comment by nimishbajaj** [comment]
I have added the filter categories in the backend/database/files folder. Please use that to define categories and filters on the UI.
